services:
  mysql:
    image: mysql:latest
    container_name: mysql_docker
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: warehouse
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warehouse
    ports:
      - 8080:8080
    environment:
      spring.datasource.url: jdbc:mysql://localhost:3333/warehouse
      spring.datasource.username: root
      spring.datasource.password: root
      spring.jpa.database-platform: org.hibernate.dialect.MySQLDialect
      spring.jpa.hibernate.ddl-auto: update

    depends_on:
      - mysql

volumes:
  mysql-data: