version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_docker
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: warehouse
    ports:
      - 3306:3306


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warehouse
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/warehouse
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - 8080:8080