logging:
  level:
    root: INFO
    com:
      capgemini:
        warehouse: INFO
spring:
  application:
    name: warehouse
  datasource:
    url: 'jdbc:mysql://localhost:3333/test'
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
